## template: jinja
#cloud-config

# User defined configurations
{% set custom_ssh_key = "" %}
{% set custom_password = "kali" %}

# Set the correct Datasource depending on the cloud
{% if cloud_name == "lxd" %}
  {% set meta = {} %}
  {% for key, value in ds.config.items() %}
    {% if key.startswith("user_") %}
      {% set _ = meta.__setitem__(key[5:], value) %}
    {% endif %}
  {% endfor %}
{% else %}
  {% set meta = ds.meta_data.get("meta") if ds.meta_data.get("meta") else {} %}
{% endif %}

# Use the cloud provided config, otherwise use the custom variables set at the top of this template
{% set ssh_key = meta.get("ssh_key") or custom_ssh_key %}
{% set password = meta.get("password") or custom_password %}

# Update
#power_state:
#  delay: 1
#  mode: reboot
#  message: Rebooting machine
#  condition: true

# No custom_packages are defined, because you should simply edit the template to add what you want
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - kali-linux-default
  - kali-desktop-xfce
  - btop
  - xserver-xorg-video-dummy

{% if ssh_key %}
ssh_authorized_keys:
  - {{ ssh_key }}
{% endif %}
password: {{ password }}
chpasswd:
  expire: false

write_files:
  - path: /root/.hushlogin
    defer: true
    permissions: '0400'
  - path: /home/kali/.hushlogin
    defer: true
    permissions: '0400'
  - path: /etc/lightdm/lightdm.conf.d/99_kali_override.conf
    defer: true
    permissions: '0644'
    content: |
      [LightDM]
      logind-check-graphical=false
      
      [SeatDefaults]
      autologin-user=kali
      autologin-user-timeout=0
  - path: /usr/share/X11/xorg.conf.d/99_rustdesk.conf.disabled
    defer: true
    permissions: '0644'
    content: |
      Section "Monitor"
        Identifier "Monitor0"
        HorizSync 28.0-80.0
        VertRefresh 48.0-75.0
        # https://arachnoid.com/modelines/
        # 1920x1080 @ 60.00 Hz (GTF) hsync: 67.08 kHz; pclk: 172.80 MHz
        Modeline "1920x1080_60.00" 172.80 1920 2040 2248 2576 1080 1081 1084 1118 -HSync +Vsync
      EndSection

      Section "Device"
        Identifier "Card0"
        Driver "dummy"
        VideoRam 256000
      EndSection

      Section "Screen"
        DefaultDepth 24
        Identifier "Screen0"
        Device "Card0"
        Monitor "Monitor0"
        SubSection "Display"
          Depth 24
          Modes "1920x1080_60.00"
        EndSubSection
      EndSection
  - path: /var/tmp/rustdesk-additional-settings.toml
    permissions: '0600'
    content: |
      allow-linux-headless = 'Y'
      verification-method = 'use-permanent-password'
      approve-mode = 'password'
      direct-server = 'Y'
      allow-remote-config-modification = 'Y'
runcmd:
  - wget https://github.com/rustdesk/rustdesk/releases/download/1.3.8/rustdesk-1.3.8-x86_64.deb -O /var/tmp/rustdesk.deb
  - apt-get install -y /var/tmp/rustdesk.deb
  - systemctl enable --now rustdesk
  - sleep 5
  - cat /var/tmp/rustdesk-additional-settings.toml | tee -a /home/kail/.config/rustdesk/RustDesk2.toml
  - rustdesk --get-id | tee /home/kali/rustdesk-id.txt
  - chown 600 /home/kali/rustdesk-id.txt
  - rustdesk --password '{{ password }}'
  - systemctl restart rustdesk
